json.id calendar_event.id
json.name calendar_event.name
json.event_date calendar_event.event_date
json.event_time calendar_event.event_time
json.location calendar_event.location
json.user_name calendar_event.user.name
json.user_location calendar_event.user.location
json.pretty_event_time calendar_event.pretty_event_time
json.pretty_event_date calendar_event.pretty_event_date
json.forecast calendar_event.forecast
